# Generated by Django 6.0.6 on 2026-07-05 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('payments', '0001_initial'),
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='subscribers.subscriber'),
        ),
        migrations.AlterUniqueTogether(
            name='sequencecounter',
            unique_together={('prefix', 'period')},
        ),
    ]
