# Generated by Django 6.0.6 on 2026-07-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('speed_profile_name', models.CharField(max_length=128)),
                ('download_rate_kbps', models.PositiveIntegerField()),
                ('upload_rate_kbps', models.PositiveIntegerField()),
                ('ip_pool', models.CharField(blank=True, max_length=128)),
                ('vlan', models.CharField(blank=True, max_length=32)),
                ('plan_type', models.CharField(choices=[('pppoe', 'PPPoE'), ('hotspot', 'Hotspot'), ('hybrid', 'Hybrid')], default='pppoe', max_length=16)),
                ('billing_cycle_days', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
