# Generated by Django 6.0.6 on 2026-07-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NasDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nas_ip_address', models.CharField(db_index=True, max_length=64, unique=True)),
                ('nas_identifier', models.CharField(blank=True, max_length=128)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('vendor', models.CharField(blank=True, max_length=128)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=16)),
                ('service_types', models.JSONField(blank=True, default=list)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
