# Generated by Django 6.0.6 on 2026-07-04 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=128)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(choices=[('start', 'Start'), ('interim', 'Interim'), ('stop', 'Stop')], db_index=True, max_length=16)),
                ('nas_ip_address', models.CharField(max_length=64)),
                ('framed_ip_address', models.CharField(blank=True, max_length=64)),
                ('session_time_seconds', models.BigIntegerField(default=0)),
                ('input_octets', models.BigIntegerField(default=0)),
                ('output_octets', models.BigIntegerField(default=0)),
                ('terminate_cause', models.CharField(blank=True, max_length=128)),
                ('payload', models.JSONField()),
                ('event_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_records', to='subscribers.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=128)),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('nas_ip_address', models.CharField(max_length=64)),
                ('nas_identifier', models.CharField(blank=True, max_length=128)),
                ('framed_ip_address', models.CharField(blank=True, max_length=64)),
                ('called_station_id', models.CharField(blank=True, max_length=128)),
                ('calling_station_id', models.CharField(blank=True, max_length=128)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('last_interim_at', models.DateTimeField(blank=True, null=True)),
                ('upload_bytes', models.BigIntegerField(default=0)),
                ('download_bytes', models.BigIntegerField(default=0)),
                ('session_time_seconds', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('online', 'Online'), ('disconnecting', 'Disconnecting')], default='online', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to='subscribers.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='AuthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=128)),
                ('action', models.CharField(choices=[('authenticate', 'Authenticate'), ('authorize', 'Authorize'), ('post_auth', 'Post Auth'), ('disconnect', 'Disconnect'), ('coa', 'CoA')], max_length=16)),
                ('result', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('ok', 'OK')], db_index=True, max_length=16)),
                ('message', models.CharField(max_length=255)),
                ('request_payload', models.JSONField()),
                ('response_payload', models.JSONField()),
                ('logged_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_logs', to='subscribers.subscriber')),
            ],
        ),
    ]
