# Generated by Django 6.0.6 on 2026-07-04 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('username', models.CharField(db_index=True, max_length=128, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('pppoe', 'PPPoE'), ('hotspot', 'Hotspot'), ('static_ip', 'Static IP'), ('dhcp', 'DHCP')], default='pppoe', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], db_index=True, default='active', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('installation_address', models.CharField(max_length=255)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('suspension_reason', models.CharField(blank=True, max_length=255)),
                ('static_ip_address', models.CharField(blank=True, max_length=64)),
                ('mac_address', models.CharField(blank=True, max_length=32)),
                ('last_online_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='customers.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='plans.plan')),
            ],
        ),
    ]
